esphome:
  name: 1stfactory-1f-motionsensor
  friendly_name: 1stFactory-1F-MotionSensor

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lpxW/QN0mn5hvbFAPCc8fCTV2KRmYo/JLHxo8e29d3c="

ota:
  - platform: esphome
    password: "3c3d94a68a754260011fbf601671cff2"

wifi:
  ssid: !secret wifi_ssid_1stfactory-1f-1st
  password: !secret wifi_password_1stfactory-1f-1st

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "1Stfactory-1F-Motionsensor"
    password: "hr40gDbXFIhg"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true
    name: "PIR Motion Sensor Large"
    device_class: motion
    filters:
      - delayed_on: 10ms       # ノイズ除去用のオン遅延（必要に応じて調整）
      - delayed_off: 10ms      # ノイズ除去用のオフ遅延（必要に応じて調整）

  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    name: "PIR Motion Sensor Small"
    device_class: motion
    filters:
      - delayed_on: 10ms       # ノイズ除去用のオン遅延（必要に応じて調整）
      - delayed_off: 10ms      # ノイズ除去用のオフ遅延（必要に応じて調整）

captive_portal: