esphome:
  name: test-garden
  friendly_name: test_garden

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "UrMsDAVR0GjtqBt0opBVVEsPENxBYnPqq3CscDrJ0dA="

ota:
  - platform: esphome
    password: "028ce28774850a714bce1f5df9b87306"

wifi:
  ssid: !secret wifi_ssid_1sthome-1f-ex1-1st
  password: !secret wifi_password_1sthome-1f-ex1-1st

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Garden Fallback Hotspot"
    password: "NpzViMeQbKMS"

switch:
  - platform: gpio
    pin: GPIO18
    name: "Relay GPIO18"
  - platform: gpio
    pin: GPIO19
    name: "Relay GPIO19"
  - platform: gpio
    pin: GPIO22
    name: "Relay GPIO22"
  - platform: gpio
    pin: GPIO23
    name: "Relay GPIO23"
    
captive_portal: